export const partialVideListMock = [
  {
    id: "12345",
    partialVideoId: "sdkfjksajlksjdfa1",
    title: "オタク IN THA HOOD : 呂布カルマ",
    videoId: "iaqgyA9PZ08",
    start: 20,
    end: 35,
    comment: "testest",
  },
  {
    id: "12346",
    partialVideoId: "dasghrrrrrrdsdhdfff",
    title: "オタク IN THA HOOD : 呂布カルマ",
    videoId: "iaqgyA9PZ08",
    start: 120,
    end: 128,
    comment: "",
  },
  {
    id: "12347",
    partialVideoId: "sdk3jks34a2lksjdfa1",
    title: "TK da 黒ぶちと戦ってみた",
    videoId: "g0avWKtqZng",
    start: 120,
    end: 140,
    comment: "tetetetetetaaaaaa",
  },
]

export const longListMock = [
  {
    id: "12348",
    partialVideoId: "shrlajkjksa2lksjdfa1",
    title: "BLACKPINK - ‘블핑하우스 (BLACKPINK HOUSE)’ EP.12-2",
    videoId: "mQSbaGNzNzc",
    start: 20,
    end: 35,
    comment: "testest",
  },
  {
    id: "12349",
    partialVideoId: "s34mjkjksa2lksjdfa1",
    title: "BLACKPINK - ‘블핑하우스 (BLACKPINK HOUSE)’ EP.12-2",
    videoId: "mQSbaGNzNzc",
    start: 90,
    end: 98,
    comment: "testest",
  },
  {
    id: "12350",
    partialVideoId: "sdkdajkjksa2lksjdfa1",
    title: "BLACKPINK - ‘블핑하우스 (BLACKPINK HOUSE)’ EP.9-1",
    videoId: "LK4UWnImijY",
    start: 300,
    end: 308,
    comment: "testest",
  },
  {
    id: "12351",
    partialVideoId: "rdkddssawksa2c09jdfa1",
    title:
      "AND STILL!!! MY BEST TEMPO FOR THAT BOUNCE VIBE USING THE MPC STUDIO BLACK",
    videoId: "pNF1lTGhDQ4",
    start: 180,
    end: 188,
    comment: "testest",
  },
  {
    id: "12352",
    partialVideoId: "swjk3jksa2q2kkfa1",
    title:
      "Brian Setzer Orchestra - Rock This Town - 7/25/1999 - Woodstock 99 East Stage (Official)",
    videoId: "LgKh8x-kpFI",
    start: 240,
    end: 252,
    comment: "testest",
  },
  {
    id: "12353",
    partialVideoId: "srd29ajkd3xks6jkzd4a1",
    title: "Les Paul & Mary Ford Absolutely Live",
    videoId: "awjTKeS9Wvo",
    start: 300,
    end: 308,
    comment: "testest",
  },
  {
    id: "12354",
    partialVideoId: "tirkapgh732934oknvvwq",
    title: "Les Paul & Mary Ford Show: World Is Waiting For The Sunrise",
    videoId: "7iGXP_UBog4",
    start: 60,
    end: 67,
    comment: "testest",
  },
  {
    id: "12355",
    partialVideoId: "jahgv3dfws049",
    title: "Les Paul & Chet Atkins 1978-07-05 NYC NBC Today Show Pt1",
    videoId: "xut3N2O42Ho",
    start: 250,
    end: 258,
    comment: "testest",
  },
  {
    id: "12356",
    partialVideoId: "ajg8mnjkryigbv4x",
    title: "Chet Atkins - Mr. Sandman (TV 1954)",
    videoId: "n-c66SJPuUI",
    start: 70,
    end: 76,
    comment: "testest",
  },
  {
    id: "12357",
    partialVideoId: "ud9iohmj,mlturgewoo9",
    title: "Sammy Davis Jr. on drums & vibes",
    videoId: "USxvJFfKXrE",
    start: 70,
    end: 76,
    comment: "testest",
  },
]
